# Generated by Django 6.0.1 on 2026-02-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0007_trek_additional_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopTrek',
        ),
        migrations.DeleteModel(
            name='WhatsNew',
        ),
        migrations.AlterField(
            model_name='treklist',
            name='activities',
            field=models.TextField(blank=True, help_text='Comma-separated values. Example: Trekking, Camping, Bonfire', null=True),
        ),
    ]
