"""
Django settings for aorbo_project.

Generated by 'django-admin startproject' using Django 5.0.1.
For more information, see https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
import sys
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default='False', cast=lambda x: x.lower() in ('true', '1', 'yes'))

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,16.170.247.251',
    cast=lambda x: [i.strip() for i in x.split(',')]
)
CSRF_TRUSTED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

# HSTS prevents downgrade attacks, X-Frame prevents clickjacking, etc.
SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS preload
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing (XSS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For reverse proxies
REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Prevent referrer leakage
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking (framing in iframes)

# In production (DEBUG=False), enforce HTTPS and secure cookies
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# SECURITY FIX: Session and CSRF cookie hardening
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript/XSS access to session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF via cookies
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF token
CSRF_COOKIE_SAMESITE = 'Strict'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'whitenoise.runserver_nostatic',
    'corsheaders',
    'rest_framework',
    'csp',
    'axes',
    'treks_app',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware',
]

# Rate limiting with django-axes
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_TEMPLATE = 'registration/lockout.html'
AXES_LOCKOUT_URL = '/locked/'
AXES_IP_WHITELIST = []
AXES_ENABLE_ACCESS_LOG = True

ROOT_URLCONF = 'aorbo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aorbo_project.wsgi.application'

# Database - Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# SSL for production
if not DEBUG and 'runserver' not in sys.argv:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_RESET_FORM = 'treks_app.forms.CustomPasswordResetForm'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


# Localhost should only be in DEBUG mode for local development
CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOWED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

CORS_ALLOW_CREDENTIALS = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'base-uri': ("'self'",),
        'connect-src': (
            "'self'",
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.google-analytics.com',  # Google Analytics data collection
            'https://cdn.jsdelivr.net', 
        ),
        'default-src': (
            "'self'",
            'https://fonts.googleapis.com',
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'font-src': (
            "'self'",
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',  # Bootstrap Icons fonts
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'form-action': ("'self'",),
        'frame-ancestors': ("'none'",),
        'frame-src': (
            "'self'",
            'https://www.google.com',
        ),
        'img-src': (
            "'self'",
            'data:',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            "https://xsconhhzyaiowokwsqne.supabase.co",
            'https://www.gstatic.com',
        ),
        'object-src': ("'none'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",  # Temporary: For inline event handlers (refactor onclick to addEventListener for production)
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',  # Google Analytics
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'script-src-elem': (
            "'self'",
            "'unsafe-inline'",  # Required for CKEditor and Django admin inline scripts
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',  # Google Analytics
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",  # Temporary: Allows inline <style> tags (refactor to external CSS for production)
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net',
            'https://www.gstatic.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
    }
}



if DEBUG:
    # Allow localhost for development only
    for directive in ["script-src", "style-src", "img-src", "font-src", "connect-src"]:
        if directive in CONTENT_SECURITY_POLICY["DIRECTIVES"]:
            CONTENT_SECURITY_POLICY["DIRECTIVES"][directive] += ("http://localhost:8000",)

SIMPLE_JWT = {
    'TOKEN_OBTAIN_PAIR_SERIALIZER': 'aorbo_project.serializers.MyTokenObtainPairSerializer',
}




